apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.MYSQL_ROOT_PASSWORD | quote }}
  MYSQL_DATABASE: {{ .Values.secret.MYSQL_DATABASE | quote }}