apiVersion: v1
kind: Service
metadata:
  name: ollama
spec:
  type: {{ .Values.ollama.service.type }}
  selector:
    app: ollama
  ports:
  - port: {{ .Values.ollama.service.port }}
    targetPort: {{ .Values.ollama.service.port }}

---

apiVersion: v1
kind: Service
metadata:
  name: bankapp-svc
spec:
  selector:
    app: bankapp
  type: {{ .Values.bankapp.service.type }}
  ports:
  - port: {{ .Values.bankapp.service.port }}
    nodePort: {{ .Values.bankapp.service.nodePort }}
    targetPort: {{ .Values.bankapp.service.port }}

