apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: {{ .Values.mysql.service.type }}
  clusterIP: None
  selector:  
    app: mysql-app
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.port }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-state
  labels: 
    app: mysql-app
spec:
  selector:
    matchLabels:
      app: mysql-app
  serviceName: mysql
  replicas: {{ .Values.mysql.replicaCount }}
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
        - name: mysql-state
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tags }}"
          ports:
            - containerPort: {{ .Values.mysql.service.port}}
              name: web
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            
            - name: MYSQL_DATABASE
              valueFrom: 
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
          readinessProbe:
            exec:
              command: ["sh","-c", "mysqladmin ping -h localhost -u root -p$MYSQL_PASSWORD"]
            initialDelaySeconds: 30
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        storageClassName: {{ .Values.mysql.storageClassName | quote }}
        accessModes: [ "ReadWriteOnce" ]
        {{- with .Values.mysql.resources }}
        resources:
            {{- toYaml . | nindent 12 }}
        {{- end }}

