sonar.projectKey=bankapp
sonar.projectName=bankapp
# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=src/main/java
sonar.tests=src/test/java

