apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: 1.14.1
    helm:
      releaseName: tempo
      valuesObject:
        tempo:
          retention: 24h
        persistence:
          enabled: true
          size: 4Gi
          storageClassName: gp2
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 500Mi
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true