apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-secret
  namespace: newbankapp
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: mysql-secret
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: bankapp/mysql
        property: password
    - secretKey: MYSQL_USER
      remoteRef:
        key: bankapp/mysql
        property: username
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: bankapp/mysql
        property: database