apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: newbankapp
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
data:
  # gitleaks:allow
  MYSQL_ROOT_PASSWORD: YmFua2FwcA==
  MYSQL_DATABASE: YmFua2FwcA==

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-host
  namespace: newbankapp
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  MYSQL_HOST: mysql-state-0.mysql.newbankapp.svc.cluster.local

