

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-host
  namespace: newbankapp
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  MYSQL_HOST: mysql-state-0.mysql.newbankapp.svc.cluster.local

