aws_region: eu-north-1

login_user: ubuntu

kubectl_version: v1.36.3

aws_access_key: "AKIATW3J5Q5SG5QFXKE3"

repo_url: https://github.com/rohit5126/AI-BankApp-DevOps.git
repo_branch: mega-project

repo_url_EKS: https://github.com/rohit5126/terraform_format_notes.git
repo_branch_EKS: main

