apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-accounts
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rohit5126/AI-BankApp-DevOps.git
    targetRevision: mega-project
    path: secret-manager
    directory:
      include: "service-accounts.yml"
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true