pipeline:
  name: bank-pipeline
  identifier: bankpipeline
  projectIdentifier: bankapp
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          gitOpsEnabled: true
          service:
            serviceRef: bankappsvc
          execution:
            steps:
              - step:
                  type: GitOpsUpdateReleaseRepo
                  name: UpdateReleaseRepo
                  identifier: updateReleaseRepo
                  timeout: 10m
                  spec:
                    variables: []
                    ignoreMissingFiles: true
              - step:
                  type: MergePR
                  name: Merge PR
                  identifier: mergePR
                  spec:
                    deleteSourceBranch: true
                  timeout: 10m
              - step:
                  type: GitOpsFetchLinkedApps
                  name: Fetch Linked Apps
                  identifier: fetchLinkedApps
                  timeout: 10m
                  spec:
                    filterByServiceEnvCluster: false
              - step:
                  type: GitOpsSync
                  name: GitOpsSync_1
                  identifier: GitOpsSync_1
                  spec:
                    prune: false
                    dryRun: false
                    applyOnly: true
                    forceApply: false
                    applicationsList:
                      - applicationName: bankappp-app
                        agentId: bankapp
                    resourcesFilter:
                      group: .*
                      kind: .*
                      name: .*
                      namespace: .*
                      label: .*
                    retryStrategy: {}
                    retry: false
                    syncOptions:
                      skipSchemaValidation: false
                      autoCreateNamespace: true
                      pruneResourcesAtLast: false
                      applyOutOfSyncOnly: true
                      replaceResources: false
                      prunePropagationPolicy: foreground
                      respectIgnoreDifferences: false
                      serverSideApply: false
                    waitTillHealthy: true
                    degradedStateTimeout: ""
                    showResourceProgress: true
                    failOnTimeout: true
                  timeout: 20m
              - step:
                  type: HarnessApproval
                  name: HarnessApproval_1
                  identifier: HarnessApproval_1
                  spec:
                    approvalMessage: Please review the following information and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    isAutoRejectEnabled: false
                    approvers:
                      userGroups:
                        - account._account_all_users
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1d
            rollbackSteps: []
          environment:
            environmentRef: bankprod
            deployToAll: false
            gitOpsClusters:
              - identifier: incluster
                agentIdentifier: bankapp
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        runMode:
          type: Auto
