aws_region: eu-north-1

login_user: ubuntu

kubectl_version: v1.36.3
helm_version: v4.2.3

aws_access_key: "AKIATW3J5Q5SG5QFXKE3"
aws_secret_key: "{{ vault_aws_secret_key }}"

repo_url: https://github.com/rohit5126/AI-BankApp-DevOps.git
repo_branch: mega-project

repo_url_EKS: https://github.com/rohit5126/terraform_format_notes.git
repo_branch_EKS: main

