name: testing
on: 
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v6

      - name: setup jdk
        uses: actions/setup-java@v6
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: code linting using checkstyle
        run: mvn checkstyle:check -Dcheckstyle.failOnViolation=false

      - name: build code with maven
        run: chmod +x mvnw && ./mvnw clean package -DskipTests -B 
        
